package crypto;

import crypto.exceptions.BadKeyException;
import crypto.exceptions.UninitialisedException;

import java.nio.file.NoSuchFileException;

/**
 * A wrapper for basic cryptographic functionality found in Java APIs, e.g.
 * javax.crypto, as well as in third party APIs, such as org.bouncycastle.crypto
 *
 * Created by Matthew Kindy II and Matt Bernhard on 11/3/2014.
 */
public interface ICryptoType {

    /**
     * Decrypts a cipherText generated by this ICryptoType.
     *
     * @param cipherText    a byte array to be decrypted
     * @return              the plaintext decrypted from the ciphertext
     *
     * @throws UninitialisedException
     */
    public byte[] decrypt(byte[] cipherText) throws UninitialisedException;

    /**
     * Encrypts a plainText according to the ICryptoType's protocol.
     *
     * @param plainText     a byte array to be encrypted
     * @return              the ciphertext of the plaintext according to the protocol
     *
     * @throws UninitialisedException if the necessary key(s) has/haven't been loaded
     */
    public byte[] encrypt(byte[] plainText) throws UninitialisedException;

    /**
     * Given a filePath, extracts the IKeys from the file and checks if they are proper keys for the
     * protocol. If they are, calls the proper submethod, else throws a BadKeyException.
     *
     * @param filePath      a String array specifying the locations of the IKeys to be loaded
     *
     * @throws BadKeyException if the ICryptoType does not support the type of IKey that was loaded
     * @throws NoSuchFileException if the file could not be found
     */
    public void loadKeys(String[] filePath) throws BadKeyException, NoSuchFileException;

    public String toString();

}
